try again

diff --git a/github/is-member-of/action.yml b/github/is-member-of/action.yml
--- a/github/is-member-of/action.yml
+++ b/github/is-member-of/action.yml
@@ -24,11 +24,10 @@ runs:
     - id: gh-api-is-member
       name: Check if user is member of the given org
       run: |
-        result="$(gh api \
+        gh api \
           -H "Accept: application/vnd.github+json" \
-          /orgs/${{ env.GH_ORG }}/members/${{ env.GH_USER }} )"
-        
-        echo "::error:: result='${result}'"
+          /orgs/${{ env.GH_ORG }}/members/${{ env.GH_USER }}
+        echo "::error:: $?"
         
         if [ 'User' = "${result}" ]; then
           echo "result=true" >> $GITHUB_OUTPUT
