is-member-of gracefully handle bots+tests (#290)
* add option to filter bots

* minor fixes + add to is-pr-author-member-of

* fix minor things

* Apply suggestions from code review

Co-authored-by: Victor Martinez <victormartinezrubio@gmail.com>

* test

* revert

* fix

* revert

* simplify and improve docs

* simplify tests

* allow gh API call to fail

* printf debug

* deal with 404

* pebkc

* printf again

* printf

* try again

* try again

* abc

* wip again

* revert to initial version

* try to make it work for users

* debug

* log statment

* another

* wip

* wip

* add missing quotes

* try again

* use return value

* wip

* allow for errors

* try to use github outpuwqipt

* use rv as debug

* qq

* aa

* aaa

* try to rely on type

* try to use status

* printf debug

* fix quote

* try with jq

* remove gh api output

* aa

* cleanup

* fix typo

* fix minor things

* add missing output from is-pr-author-member-of

* cleanup

* fix typo

* invert condition

* fallback to rely on 404 or not

* post-review changes

---------

Co-authored-by: Victor Martinez <victormartinezrubio@gmail.com>

diff --git a/github/is-member-of/action.yml b/github/is-member-of/action.yml
--- a/github/is-member-of/action.yml
+++ b/github/is-member-of/action.yml
@@ -1,6 +1,6 @@
 name: 'github/is-member-of'
 
-description: Check whether the given GitHub user is member of the given GitHub organization
+description: Check whether the given GitHub user is a member of the given GitHub organization.
 
 inputs:
   github-user:
@@ -10,12 +10,12 @@ inputs:
     description: 'The GitHub org'
     required: true
   github-token:
-    description: 'The GitHub access token.'
+    description: 'The GitHub access token'
     required: true
 
 outputs:
   result:
-    description: 'The result in either true or false'
+    description: '`true` if user is member of the GitHub org, `false` if not a member or a bot'
     value: ${{ steps.gh-api-is-member.outputs.result }}
 
 runs:
@@ -24,11 +24,18 @@ runs:
     - id: gh-api-is-member
       name: Check if user is member of the given org
       run: |
-        if gh api \
+        # required because 'gh api' will return non-zero return code for 404s to indicate lack of membership
+        set +e
+        # gh api will return a 404 with 'status' JSON attribute to indicate lack of membership
+        result=$(gh api \
           -H "Accept: application/vnd.github+json" \
-          /orgs/${{ env.GH_ORG }}/members/${{ env.GH_USER }} ; then
+          /orgs/${{ env.GH_ORG }}/members/${{ env.GH_USER }} 2>/dev/null | jq -r '.status // "member"' )
+        set -e
+
+        if [[ '404' != "${result}" ]]; then
           echo "result=true" >> $GITHUB_OUTPUT
         else
+          # 404 or unknown user type
           echo "result=false" >> $GITHUB_OUTPUT
         fi
       env:
