post-review changes

diff --git a/github/is-member-of/action.yml b/github/is-member-of/action.yml
--- a/github/is-member-of/action.yml
+++ b/github/is-member-of/action.yml
@@ -24,12 +24,13 @@ runs:
     - id: gh-api-is-member
       name: Check if user is member of the given org
       run: |
-        # required because 'gh api' will return non-zero for 404s to indicate lack of membership
+        # required because 'gh api' will return non-zero return code for 404s to indicate lack of membership
         set +e
-        # gh api will return a 404 with status to indicate lack of membership
+        # gh api will return a 404 with 'status' JSON attribute to indicate lack of membership
         result=$(gh api \
           -H "Accept: application/vnd.github+json" \
           /orgs/${{ env.GH_ORG }}/members/${{ env.GH_USER }} 2>/dev/null | jq -r '.status // "member"' )
+        set -e
 
         if [[ '404' != "${result}" ]]; then
           echo "result=true" >> $GITHUB_OUTPUT
@@ -37,7 +38,6 @@ runs:
           # 404 or unknown user type
           echo "result=false" >> $GITHUB_OUTPUT
         fi
-        set -e
       env:
         GH_TOKEN: ${{ inputs.github-token }}
         GH_USER: ${{ inputs.github-user }}
