feat(changed-files): add changed output (#355)
* feat(changed-files): add changed output

testing

exclude

add e2e tests

fix

exclude linting

dist

fix

docs

* fix

* fix

* fix]

* remove

diff --git a/.github/workflows/test-github-changed-files.yml b/.github/workflows/test-github-changed-files.yml
--- a/.github/workflows/test-github-changed-files.yml
+++ b/.github/workflows/test-github-changed-files.yml
@@ -13,6 +13,12 @@ on:
     paths:
       - '.github/workflows/test-github-changed-files.yml'
       - 'github/changed-files/**'
+  pull_request:
+    branches:
+      - main
+    paths:
+      - '.github/workflows/test-github-changed-files.yml'
+      - 'github/changed-files/**'
 
 permissions:
   contents: read
@@ -95,3 +101,62 @@ jobs:
         run: |
           echo "::error ::Modified files are not correct"
           exit 1
+
+  test-changed-files:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v5
+      - uses: ./git/setup
+      - name: Add files
+        run: |
+          touch file.json
+          touch file.yaml
+          touch file.bak
+          git rm README.md
+          echo "" >> .pre-commit-config.yaml
+          git add file.json file.yaml file.bak .pre-commit-config.yaml
+          git commit -m "Changed files"
+      - uses: ./github/changed-files
+        id: changed-files
+        with:
+          base-ref: "HEAD^1"
+          ref: "HEAD"
+          filter: '["*.yaml","*.json","*.md"]'
+
+      - name: debug info
+        run: |
+          echo "count=${{ steps.changed-files.outputs.count }}"
+          echo "count-deleted=${{ steps.changed-files.outputs.count-deleted }}"
+          echo "count-added=${{ steps.changed-files.outputs.count-added }}"
+          echo "count-modified=${{ steps.changed-files.outputs.count-modified }}"
+
+      - name: test count
+        if: ${{ steps.changed-files.outputs.count != 4 }}
+        run: |
+          echo "::error ::Count is not 4"
+          exit 1
+
+      - name: test added files
+        if: ${{ steps.changed-files.outputs.count-added != 2 }}
+        run: |
+          echo "::error ::Added files are not correct"
+          exit 1
+
+      - name: test modified files
+        if: ${{ steps.changed-files.outputs.count-modified != 1 }}
+        run: |
+          echo "::error ::Modified files are not correct"
+          exit 1
+
+      - name: test deleted files
+        if: ${{ steps.changed-files.outputs.count-deleted != 1 }}
+        run: |
+          echo "::error ::Deleted files are not correct"
+          exit 1
+
+      - name: test changed files
+        run: |
+          echo "${{ steps.changed-files.outputs.changed }}" | grep README.md
+          echo "${{ steps.changed-files.outputs.changed }}" | grep 'file.json'
+          echo "${{ steps.changed-files.outputs.changed }}" | grep 'file.yaml'
+          echo "${{ steps.changed-files.outputs.changed }}" | grep '.pre-commit-config.yaml'
